use different return value if flash operation failed

diff --git a/update-uboot b/update-uboot
--- a/update-uboot
+++ b/update-uboot
@@ -219,12 +219,19 @@ sleep ${UBM_MENU_TIMEOUT} && run ${UBM_DEFAULT}
 echo "Building uboot-manager script..."
 mkimage -A arm -O linux -T script -C none -a 0x00000000 -e 0x00000000 -n "uboot-manager" -d "${UBM_ENV_FILE}" "${UBM_SYSROOT}/${UBM_FW_DIR}/boot.scr" || { echo "error creating uboot-manager script image"; exit 1; }
 
-if [ "${UBM_FLASH_UBOOT}" == "1" ]; then
-	[ -f "${UBM_SYSROOT}/${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}" ] || { echo "ERROR: u-boot binary \"${UBM_SYSROOT}/${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}\" not found"; exit 1; }
+EXIT_CODE=0
 
-	echo "Flashing ${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}..."
-	dd if="${UBM_SYSROOT}/${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}" of="${UBM_FLASH_DEVICE}" ${UBM_FLASH_DD_PARAMS} conv=fsync
+if [ "${UBM_FLASH_UBOOT}" == "1" ]; then
+	if [ -f "${UBM_SYSROOT}/${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}" ]; then
+		echo "Flashing ${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}..."
+		dd if="${UBM_SYSROOT}/${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}" of="${UBM_FLASH_DEVICE}" ${UBM_FLASH_DD_PARAMS} conv=fsync
+	else
+		echo "ERROR: u-boot binary \"${UBM_SYSROOT}/${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}\" not found"
+		EXIT_CODE=2
+	fi
 fi
 
 [ "${UBM_SHOW_ENV}" != "" ] && { echo -e "\n\nResulting script:\n"; cat "${UBM_ENV_FILE}"; }
 rm "${UBM_ENV_FILE}"
+
+exit ${EXIT_CODE}
