look in UBM_FLASH_SOURCE_DIR for uboot binary

diff --git a/update-uboot b/update-uboot
--- a/update-uboot
+++ b/update-uboot
@@ -21,7 +21,6 @@ UBM_KERNEL_ARGS=${UBM_KERNEL_ARGS-rootfstype=btrfs quiet splash logo.nologo}
 UBM_MENU_TIMEOUT=${UBM_MENU_TIMEOUT-2}
 UBM_DEFAULT=${UBM_DEFAULT-boot0}
 UBM_PREPEND_FW_KERNEL_ARGS=${UBM_PREPEND_FW_KERNEL_ARGS-1}
-UBM_FILTER_FW_KERNEL_ARGS=""
 UBM_PRELOADED_DEVTREE=${UBM_PRELOADED_DEVTREE-0}
 UBM_DEVTREE_FILE=${UBM_DEVTREE_FILE-bcm2709-rpi-2-b.dtb}
 UBM_INITRD_LADDR_ID=${UBM_INITRD_LADDR_ID-ramdisk_addr_r}
@@ -33,7 +32,9 @@ UBM_PART_ID=${UBM_PART_ID-mmc 0:1}
 UBM_SUBVOL_SEARCH=${UBM_SUBVOL_SEARCH-0}
 
 UBM_FLASH_UBOOT=${UBM_FLASH_UBOOT-0}
+UBM_FLASH_SOURCE_DIR=${UBM_FLASH_SOURCE_DIR-boot}
 UBM_FLASH_BINARY=${UBM_FLASH_BINARY-u-boot.imx}
+UBM_FLASH_DD_PARAMS=${UBM_FLASH_DD_PARAMS-bs=1k seek=1}
 if [ -z "${UBM_FLASH_DEVICE}" ]; then
 	if [[ ${UBM_LOCAL_ROOT_DEV} =~ [0-9]$ ]] && [ -b ${UBM_LOCAL_ROOT_DEV::-1} ]; then
 		UBM_FLASH_DEVICE="${UBM_LOCAL_ROOT_DEV::-1}"
@@ -50,7 +51,6 @@ if [ -z "${UBM_FLASH_DEVICE}" ]; then
 		exit 1
 	fi
 fi
-UBM_FLASH_DD_PARAMS=${UBM_FLASH_DD_PARAMS-bs=1k seek=1}
 
 UBM_FS_LOAD=${UBM_FS_LOAD-load}
 UBM_FS_WRITE=${UBM_FS_WRITE-write}
@@ -239,10 +239,10 @@ echo "Building uboot-manager script..."
 mkimage -A arm -O linux -T script -C none -a 0x00000000 -e 0x00000000 -n "uboot-manager" -d "${UBM_ENV_FILE}" "${UBM_SYSROOT}/${UBM_FW_DIR}/boot.scr" || { echo "error creating uboot-manager script image"; exit 1; }
 
 if [ "${UBM_FLASH_UBOOT}" == "1" ]; then
-	[ -f "${UBM_SYSROOT}/${UBM_FW_DIR}/${UBM_FLASH_BINARY}" ] || { echo "ERROR: u-boot binary \"${UBM_SYSROOT}/${UBM_FW_DIR}/${UBM_FLASH_BINARY}\" not found"; exit 1; }
+	[ -f "${UBM_SYSROOT}/${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}" ] || { echo "ERROR: u-boot binary \"${UBM_SYSROOT}/${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}\" not found"; exit 1; }
 
 	echo "Flashing ${UBM_FLASH_BINARY}..."
-	dd if="${UBM_SYSROOT}/${UBM_FW_DIR}/${UBM_FLASH_BINARY}" of="${UBM_FLASH_DEVICE}" ${UBM_FLASH_DD_PARAMS} conv=fsync
+	dd if="${UBM_SYSROOT}/${UBM_FLASH_SOURCE_DIR}/${UBM_FLASH_BINARY}" of="${UBM_FLASH_DEVICE}" ${UBM_FLASH_DD_PARAMS} conv=fsync
 fi
 
 [ "${UBM_SHOW_ENV}" != "" ] && { echo -e "\n\nResulting script:\n"; cat "${UBM_ENV_FILE}"; }
